recipes-kernel/nvidia-kernel-oot: Fix build failure on Scarthgap
This change fixes the following error:
    ERROR: balena-image-flasher-1.0-r0 do_rootfs: Unable to find package
    with name 'kernel-module-lan743x-5.15.148-l4t-r36.4-1012.12' in SPDX file

The error occured only on the devices which install the lan743x driver,
which is provided by both the kernel package as well as by nvidia-kernel-oot.

Signed-off-by: Alexandru Costache <alexandru@balena.io>